services:
  hummingbot-gateway:
    restart: always
    container_name: hummingbot-gateway
    build:
      context: .
      dockerfile: Dockerfile
    image: VeXHarbinger/gateway:feature-clmm-add-remove-liquidity
    ports:
      - "15888:15888"
    volumes:
      - "./gateway-files/conf:/home/gateway/conf"
      - "./gateway-files/logs:/home/gateway/logs"
      - "./certs:/home/gateway/certs"
      - gateway-wallets:/home/gateway/conf/wallets
    environment:
      GATEWAY_PASSPHRASE: admin
      DEV: 'true'

